"""Shared PDF/Excel builders for the Reporting & Analytics module.

Each report route shapes its data into (title, generated_by, filters,
summary_stats, table_headers, table_rows) and calls one of these two
functions — all document layout/styling lives here once, not per report.
"""
import io
import re

from flask import current_app
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.utils import utcnow

PRIMARY_HEX = "#0f6f8f"


def _format_filters(filters):
    applied = {k: v for k, v in filters.items() if v}
    if not applied:
        return "None"
    return ", ".join(f"{k.replace('_', ' ').title()}: {v}" for k, v in applied.items())


def build_pdf_report(title, generated_by, filters, summary_stats, table_headers, table_rows):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        rightMargin=1.5 * cm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], textColor=colors.HexColor(PRIMARY_HEX), fontSize=18)
    meta_style = ParagraphStyle("ReportMeta", parent=styles["Normal"], textColor=colors.HexColor("#475467"), fontSize=9)

    org_name = current_app.config.get("APP_NAME", "Smart Water Point Monitoring System")
    elements = [
        Paragraph(org_name, meta_style),
        Paragraph(title, title_style),
        Paragraph(f"Generated by: {generated_by.full_name} ({generated_by.role})", meta_style),
        Paragraph(f"Generated on: {utcnow().strftime('%Y-%m-%d %H:%M UTC')}", meta_style),
        Paragraph(f"Filters applied: {_format_filters(filters)}", meta_style),
        Spacer(1, 0.5 * cm),
    ]

    if summary_stats:
        summary_rows = [[key.replace("_", " ").title(), str(value)] for key, value in summary_stats.items()]
        summary_table = Table(summary_rows, colWidths=[6 * cm, 4 * cm])
        summary_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eaf3f6")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d0d5dd")),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        elements.extend([summary_table, Spacer(1, 0.7 * cm)])

    if table_rows:
        data = [table_headers] + [[str(cell) for cell in row] for row in table_rows]
        data_table = Table(data, repeatRows=1)
        style = TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(PRIMARY_HEX)),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d0d5dd")),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
        for i in range(1, len(data)):
            if i % 2 == 0:
                style.add("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f6f8fb"))
        data_table.setStyle(style)
        elements.append(data_table)
    else:
        elements.append(Paragraph("No data available for the selected filters.", meta_style))

    def _footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#667085"))
        canvas.drawRightString(landscape(A4)[0] - 1.5 * cm, 1 * cm, f"Page {doc_.page}")
        canvas.restoreState()

    doc.build(elements, onFirstPage=_footer, onLaterPages=_footer)
    buffer.seek(0)
    return buffer


def build_excel_report(title, generated_by, filters, summary_stats, table_headers, table_rows):
    wb = Workbook()
    ws = wb.active
    ws.title = re.sub(r'[\\/*?:\[\]]', '-', title)[:31]

    org_name = current_app.config.get("APP_NAME", "Smart Water Point Monitoring System")
    bold = Font(bold=True)
    header_fill = PatternFill(start_color="0F6F8F", end_color="0F6F8F", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")

    ws.append([org_name])
    ws["A1"].font = Font(bold=True, size=12)
    ws.append([title])
    ws["A2"].font = Font(bold=True, size=14, color="0F6F8F")
    ws.append([f"Generated by: {generated_by.full_name} ({generated_by.role})"])
    ws.append([f"Generated on: {utcnow().strftime('%Y-%m-%d %H:%M UTC')}"])
    ws.append([f"Filters applied: {_format_filters(filters)}"])
    ws.append([])

    if summary_stats:
        for key, value in summary_stats.items():
            row = [key.replace("_", " ").title(), value]
            ws.append(row)
            ws.cell(row=ws.max_row, column=1).font = bold
        ws.append([])

    header_row_num = ws.max_row + 1
    ws.append(table_headers)
    for col in range(1, len(table_headers) + 1):
        cell = ws.cell(row=header_row_num, column=col)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")

    for row in table_rows:
        ws.append(list(row))

    ws.freeze_panes = ws.cell(row=header_row_num + 1, column=1)
    for col_cells in ws.columns:
        max_len = max((len(str(c.value)) for c in col_cells if c.value is not None), default=10)
        ws.column_dimensions[col_cells[0].column_letter].width = min(max(max_len + 2, 10), 40)

    buffer = io.BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer
