"""add water_sources table and water_source_id to water_points

Revision ID: 236b669f40e4
Revises: c158a8bdc832
Create Date: 2026-07-07 22:36:58.720408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236b669f40e4'
down_revision = 'c158a8bdc832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('catchment', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('usage_types', sa.Text(), nullable=True),
    sa.Column('industrial_pressure_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('water_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_source_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_water_points_water_source_id', 'water_sources', ['water_source_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_points', schema=None) as batch_op:
        batch_op.drop_constraint('fk_water_points_water_source_id', type_='foreignkey')
        batch_op.drop_column('water_source_id')

    op.drop_table('water_sources')
    # ### end Alembic commands ###
