"""baseline schema (users, water_points, notifications, audit_logs)

These four tables predate Alembic tracking in this project - they were only
ever created via `db.create_all()` (see run.py's `init-db` CLI command), never
through a migration. That meant a `flask db upgrade` on a genuinely empty
database would skip them entirely and only create maintenance_tasks /
task_status_history / report_logs, leaving the app unable to start. This
revision is inserted as the new root of the migration chain (down_revision =
None) so a fresh `flask db upgrade` produces the full schema in FK-safe order:
this baseline first, then 90489408fe07 (which adds maintenance_tasks /
task_status_history, both FK-referencing users/water_points).

Existing databases (including this project's own dev smart_water.db) are
already stamped past this point in alembic_version, so `flask db upgrade`
against them is a no-op for this revision - nothing here re-runs against a
database that already has these tables. Any other pre-existing database that
was seeded via `flask init-db` rather than migrations will need
`flask db stamp <revision-of-a1b2c3d4e5f6-or-later>` before upgrading, to
tell Alembic these tables already exist.

Revision ID: 87ca337431cf
Revises:
Create Date: 2026-07-07 20:44:04.837105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ca337431cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_point_id', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('cell', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('technology_type', sa.String(length=50), nullable=False),
    sa.Column('year_installed', sa.Integer(), nullable=True),
    sa.Column('population_served', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('current_status', sa.String(length=20), nullable=True),
    sa.Column('risk_probability', sa.Float(), nullable=True),
    sa.Column('last_prediction_date', sa.DateTime(), nullable=True),
    sa.Column('monthly_rainfall', sa.Float(), nullable=True),
    sa.Column('rainfall_month', sa.String(length=10), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('water_point_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_points')
    op.drop_table('notifications')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
