"""add sector cell village to users

Revision ID: c158a8bdc832
Revises: a1b2c3d4e5f6
Create Date: 2026-07-07 21:22:49.990270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c158a8bdc832'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cell', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('village', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('village')
        batch_op.drop_column('cell')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
